# Base image
FROM python:3.10

# Setting the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Installing the required libraries
RUN pip install --no-cache-dir -r requirements.txt

# Run data_ingestion.py when the container launches
CMD ["python", "data_ingestion.py"]