# Base image
FROM python:3.8-slim

# Setting the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Installing the required libraries
RUN pip install --no-cache-dir -r requirements.txt

# Run data_summary when the container launches
CMD ["python", "data_summary.py"]